[minder]
name = "OrbitTTSEdgeTTS" # Required parameter
version = "1.0.0" # Required parameter
description = "Асинхронный модуль преобразования текста в речь (TTS) с использованием edge-tts и воспроизведением через sounddevice. Поддерживает разбиение текста на чанки, удаление хвостовой тишины, параллельную генерацию и воспроизведение, а также корректную остановку. Изначально создавался для системы Orbit." # Short description. Required parameter
authors = [ # The list of authors. If there is only one author, make a list with one dictionary.
    { name = "esolment", email = "esolment@gmail.com" }
]
readme = "README.md" #  README file
urls = [ # Links. For example, a repository, an official website, etc.
    "https://github.com/esolment/OrbitTTSEdgeTTS"
]
license = "MIT" # Minder license
python = "==3.11.*" # Required Python version
mind = ">=1.0.0" # Required Mind version
install-requires = [ # List of required libraries
    "guardin-mind",
    "edge-tts",
    "sounddevice",
    "soundfile",
    "concurrent_log_handler",
    "numpy"
]